config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes

  root "recipes#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    
    has_many :ingredients, dependent: :destroy, inverse_of: :recipe
    accepts_nested_attributes_for :ingredients,
                                    reject_if: proc { |attributes| attributes['name'].blank? },
                                    allow_destroy: true


    
    has_many :instructions, dependent: :destroy, inverse_of: :recipe
    accepts_nested_attributes_for :instructions,
                                    reject_if: proc { |attributes| attributes['step'].blank? },
                                    allow_destroy: true

    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 3, maximum: 50 }
    validates :user_id, presence: true
   
    
    has_attached_file :image, styles: { medium: "400x400#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes 
  before_save { self.email = email.downcase }
  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :find_recipe, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def index
        @recipes = Recipe.all.order("created_At DESC")
    end

    def new
        @recipe = current_user.recipes.build
    end
    
    def show
    end

    def create
        @recipe = current_user.recipes.build(recipe_params)
        if @recipe.save
            flash[:success] = "Recipe Successfully Created!!"
            redirect_to @recipe
            
        else
            render 'new'
        end
    end
    
    def edit
    end

    def update
        if @recipe.update(recipe_params)
            flash[:success] = "Recipe Successfully Updated!!"
            redirect_to @recipe
        else
            render 'edit'
        end
    end

    def destroy
        @recipe.destroy
        flash[:danger] = "Recipe Successfully Deleted !!"
        redirect_to root_path, notice: "Deleted successfully!"
    end

    private
    def  recipe_params
        params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], instructions_attributes: [:id, :step, :_destroy])
    end

    def find_recipe
        @recipe = Recipe.find(params[:id])
    end

    def require_same_user
        if current_user != @recipe.user and !current_user.admin?
            flash[:danger] = "You can only edit or destroy your own recipe"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_footer.html.haml
.container
  %footer.footer
    %small
      Copyright &amp;copy:
      %a{:href => "#"} Subash Khatri
    %nav
      %ul
        %li.nav-item
          = link_to "Recipes", recipes_path, class: 'footer-recipe'

app/views/layouts/_messages.html.haml
.row
  .col-sm-10
    - flash.each do |name, msg|
      %div{:class => "alert alert-#{"#{name}"}"}
        %a.close{"data-dismiss" => "alert", :href => "#"} ×
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TestApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  %nav.navbar.navbar-default
    .container  
      .navbar-brand= link_to "RMS", root_path
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Recipie", new_recipe_path
          %li= link_to "My Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
          %li= 'Admin' if current_user.admin?
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path

  
  .container
    = render "layouts/messages"
    
    = yield
  = render 'layouts/footer'  

app/views/recipes/_form.html.haml
= render 'shared/errors', obj: @recipe
= simple_form_for @recipe, html: { multipart: true} do |f|    
    .panel-body 
        = f.input :title, input_html: { class: 'form-control'}
        = f.input :description, input_html: { class: 'form-control'}
        %br/
        = f.file_field :image, input_html: { class: 'form-control'}

        .row
            .col-md-6
                %h3 Ingredients                
                #ingredients
                    = f.simple_fields_for :ingredients do |ingredient|
                        = render 'ingredient_fields', f: ingredient
                    .links
                        = link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"
            .col-md-6
                %h3 Instructions
                #instructions
                    = f.simple_fields_for :instructions do |instruction|
                        = render 'instruction_fields', f: instruction
                    .links 
                        = link_to_add_association 'Add Instruction', f, :instructions, class: "btn btn-default add-button"                           

    = f.button :submit, class: 'btn- btn-primary' 

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
	.nested-fields
		.field
			= f.input :name, input_html: { class: 'form-input form-control' }
			= link_to_remove_association 'Remove', f, class: 'form-button btn btn-default'

app/views/recipes/_instruction_fields.html.haml
.form-inline.clearfix
    .nested-fields
        .field
            = f.input :step, input_html: { class: 'form-input form-control' }
            = link_to_remove_association 'remove step', f, class: 'form-button btn btn-default'

app/views/recipes/edit.html.haml
%h1 Edit Recipe

= render 'form'

app/views/recipes/index.html.haml
%h1 Welcome to Recipe Management System  
- @recipes.each_slice(3) do |recipe|
    .row
        - recipe.each do |rec|
            .col-md-4
                .recipe
                    .image_wrapper
                        = link_to rec do 
                            = image_tag rec.image.url(:medium)
                    %h2= link_to rec.title, rec


   

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/recipes/show.html.haml
.main_content
	#recipe_top.row
		.col-md-4
			= image_tag @recipe.image.url(:medium), class: "recipe_image"
		.col-md-8
			#recipe_info
				%h1= @recipe.title
				%p.description= @recipe.description
				%p
					Submitted by
					= @recipe.user.email

	.row
		.col-md-6
			#ingredients
				%h2 Ingredients
				%ul
					- @recipe.ingredients.each do |ingredient|
						%li= ingredient.name

		.col-md-6
			#instructions
				%h2 Instructions
				%ul
					- @recipe.instructions.each do |instruction|
						%li= instruction.step

	.row
		.col-md-12
			= link_to "Back", root_path, class: "btn btn-info"
			- if user_signed_in? && (current_user == @recipe.user || current_user.admin?) 
				= link_to "Edit", edit_recipe_path, class: "btn btn-primary"
				= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger"

app/views/shared/_errors.html.haml
- if obj.errors.any?
  .row
    .col-xs-8{:style => "margin-left: 15%; "}
      .card
        .card-body{:style => "background-color: rgb(152, 190, 250);"}
          %h2.card-title{:style => "color:red;"}
            = pluralize(obj.errors.count, "error")
            prohibited this from being saved:
          .card-body{:style => "color:red;"}
            %ul
              - obj.errors.full_messages.each do |msg|
                %li
                  = msg
              %ul